In [46]:
import pandas as pd

In [47]:
df_chick1=pd.read_clipboard()
df_chick1 


#Datasets  #sum_counts_chick1
0                Bacteroides fragilis             1914737
1        Bacteroides thetaiotaomicron              314848
2            Fusobacterium mortiferum             2437366
3              Fusobacterium ulcerans             1743746
4                Fusobacterium varium            10458290
5        Fusobacterium sp. HMSC073F01              568245
6          Aquincola tertiaricarbonis              293069
7                 Tepidicella xavieri              197557
8                  Campylobacter coli              165055
9                    Escherichia coli             3641933
10                Salmonella enterica              149880
11                  Proteus mirabilis              273832
12  Pseudogracilibacillus auburnensis              872793
13                 Enterococcus avium             2241906
14         Enterococcus casseliflavus              882596
15               Enterococcus cecorum             5056210
16              Enterococcus faecalis             6839153
17               Enterococcus faecium             1041309
18            Enterococcus gallinarum            10934723
19                 Enterococcus hirae              452245
20       Enterococcus saccharolyticus              283563
21            Enterococcus sp. HSIEG1              697748
22               Lactobacillus agilis              727582
23           Lactobacillus amylovorus              476955
24             Lactobacillus aviarius             1013914
25            Lactobacillus crispatus              231412
26          Lactobacillus delbrueckii              242734
27           Lactobacillus gigeriorum             1729870
28            Lactobacillus ingluviei              601041
29            Lactobacillus johnsonii              342670
30          Lactobacillus kitasatonis             1213713
31           Lactobacillus saerimneri              317632
32           Lactobacillus salivarius             1106687
33           [Clostridium] spiroforme              184464
34          Faecalicoccus pleomorphus              280670
35                  Veillonella magna              195247

In [48]:
df_chick2=pd.read_clipboard()
df_chick2


#Datasets  #sum_counts_chick2
0                uncultured bacterium               50266
1                Bacteroides fragilis              121839
2                Bacteroides plebeius               40731
3          uncultured Bacteroides sp.               36017
4       Sediminibacterium goheungense               69552
..                                ...                 ...
62          Faecalitalea cylindroides               89555
63       Massilimicrobiota timonensis               34221
64             Traorella massiliensis               49402
65  Phascolarctobacterium sp. CAG:266               59639
66              Megamonas rupellensis               39882

[67 rows x 2 columns]

In [49]:
dfmerged = df_chick1.merge(df_chick2, on = "#Datasets", how = 'outer')
dfmerged 

#Datasets  #sum_counts_chick1  #sum_counts_chick2
0                Bacteroides fragilis           1914737.0            121839.0
1        Bacteroides thetaiotaomicron            314848.0                 NaN
2            Fusobacterium mortiferum           2437366.0            505125.0
3              Fusobacterium ulcerans           1743746.0                 NaN
4                Fusobacterium varium          10458290.0                 NaN
..                                ...                 ...                 ...
77          Faecalitalea cylindroides                 NaN             89555.0
78       Massilimicrobiota timonensis                 NaN             34221.0
79             Traorella massiliensis                 NaN             49402.0
80  Phascolarctobacterium sp. CAG:266                 NaN             59639.0
81              Megamonas rupellensis                 NaN             39882.0

[82 rows x 3 columns]

In [50]:
#this is a panda dataframe; if you are using a numpy dataframe then you cannot use fillna, instead use X.replace(np.nan,0)
dfmerged = dfmerged.fillna(0)
dfmerged = dfmerged.T
dfmerged

0                             1   \
#Datasets           Bacteroides fragilis  Bacteroides thetaiotaomicron   
#sum_counts_chick1           1.91474e+06                        314848   
#sum_counts_chick2                121839                             0   

                                          2                       3   \
#Datasets           Fusobacterium mortiferum  Fusobacterium ulcerans   
#sum_counts_chick1               2.43737e+06             1.74375e+06   
#sum_counts_chick2                    505125                       0   

                                      4                             5   \
#Datasets           Fusobacterium varium  Fusobacterium sp. HMSC073F01   
#sum_counts_chick1           1.04583e+07                        568245   
#sum_counts_chick2                     0                             0   

                                            6                    7   \
#Datasets           Aquincola tertiaricarbonis  Tepidicella xavieri   
#sum_counts_chick1                      293069               197557   
#sum_counts_chick2                      310784                    0   

                                    8                 9   ...  \
#Datasets           Campylobacter coli  Escherichia coli  ...   
#sum_counts_chick1              165055       3.64193e+06  ...   
#sum_counts_chick2               43588            208289  ...   

                                       72                           73  \
#Datasets           Romboutsia timonensis  Terrisporobacter glycolicus   
#sum_counts_chick1                      0                            0   
#sum_counts_chick2                  46875                       228688   

                                              74  \
#Datasets           Terrisporobacter othiniensis   
#sum_counts_chick1                             0   
#sum_counts_chick2                        175630   

                                                 75  \
#Datasets           Peptostreptococcaceae bacterium   
#sum_counts_chick1                                0   
#sum_counts_chick2                           339262   

                                               76                         77  \
#Datasets           Pseudoflavonifractor sp. An85  Faecalitalea cylindroides   
#sum_counts_chick1                              0                          0   
#sum_counts_chick2                          40100                      89555   

                                              78                      79  \
#Datasets           Massilimicrobiota timonensis  Traorella massiliensis   
#sum_counts_chick1                             0                       0   
#sum_counts_chick2                         34221                   49402   

                                                   80                     81  
#Datasets           Phascolarctobacterium sp. CAG:266  Megamonas rupellensis  
#sum_counts_chick1                                  0                      0  
#sum_counts_chick2                              59639                  39882  

[3 rows x 82 columns]

In [51]:
import numpy as npy

In [52]:
from skbio.stats.composition import multiplicative_replacement as MR

In [60]:
#MAKE AN ARRAY IN ORDER TO APPLY MR
ind=["#sum_counts_chick1", "#sum_counts_chick2"]#look for columns 
X = npy.array(dfmerged.T[ind], dtype="float64")
X = X.T
X

array([[ 1914737.,   314848.,  2437366.,  1743746., 10458290.,   568245.,
          293069.,   197557.,   165055.,  3641933.,   149880.,   273832.,
          872793.,  2241906.,   882596.,  5056210.,  6839153.,  1041309.,
        10934723.,   452245.,   283563.,   697748.,   727582.,   476955.,
         1013914.,   231412.,   242734.,  1729870.,   601041.,   342670.,
         1213713.,   317632.,  1106687.,   184464.,   280670.,   195247.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0.,        0.,        0.,        0.,
               0.,        0.,        0

In [61]:
MultX=MR(X)
MultX

array([[3.16278665e-02, 5.20069885e-03, 4.02607180e-02, 2.88034157e-02,
        1.72751349e-01, 9.38634235e-03, 4.84095059e-03, 3.26327136e-03,
        2.72639924e-03, 6.01579072e-02, 2.47573668e-03, 4.52319140e-03,
        1.44169045e-02, 3.70320852e-02, 1.45788317e-02, 8.35191125e-02,
        1.12969989e-01, 1.72004730e-02, 1.80621129e-01, 7.47023977e-03,
        4.68392929e-03, 1.15254892e-02, 1.20182910e-02, 7.87840266e-03,
        1.67479589e-02, 3.82249251e-03, 4.00951073e-03, 2.85742102e-02,
        9.92807081e-03, 5.66026614e-03, 2.00482639e-02, 5.24668531e-03,
        1.82803950e-02, 3.04699954e-03, 4.63614235e-03, 3.22511449e-03,
        1.48720999e-04, 1.48720999e-04, 1.48720999e-04, 1.48720999e-04,
        1.48720999e-04, 1.48720999e-04, 1.48720999e-04, 1.48720999e-04,
        1.48720999e-04, 1.48720999e-04, 1.48720999e-04, 1.48720999e-04,
        1.48720999e-04, 1.48720999e-04, 1.48720999e-04, 1.48720999e-04,
        1.48720999e-04, 1.48720999e-04, 1.48720999e-04, 1.487209

In [62]:
from skbio.stats.composition import clr

In [63]:
clrX=clr(MultX)

clrX

array([[ 3.41529255,  1.61004698,  3.65663022,  3.32174795,  5.11310724,
         2.20050966,  1.53836507,  1.14398415,  0.96423575,  4.05822686,
         0.86779197,  1.47047178,  2.62965541,  3.57303867,  2.64082456,
         4.38632947,  4.68837617,  2.80619085,  5.1576556 ,  1.97218106,
         1.50539132,  2.405815  ,  2.4476837 ,  2.02537914,  2.77953036,
         1.30215667,  1.34992319,  3.31375854,  2.25662015,  1.69472488,
         2.95939653,  1.61885048,  2.86708314,  1.07541132,  1.4951366 ,
         1.13222242, -1.94442925, -1.94442925, -1.94442925, -1.94442925,
        -1.94442925, -1.94442925, -1.94442925, -1.94442925, -1.94442925,
        -1.94442925, -1.94442925, -1.94442925, -1.94442925, -1.94442925,
        -1.94442925, -1.94442925, -1.94442925, -1.94442925, -1.94442925,
        -1.94442925, -1.94442925, -1.94442925, -1.94442925, -1.94442925,
        -1.94442925, -1.94442925, -1.94442925, -1.94442925, -1.94442925,
        -1.94442925, -1.94442925, -1.94442925, -1.9

In [67]:
dfmerged = dfmerged.T
clrX = npy.transpose(clrX)
clrX


array([[ 3.41529255,  0.87924374],
       [ 1.61004698, -3.04682329],
       [ 3.65663022,  2.30134917],
       [ 3.32174795, -3.04682329],
       [ 5.11310724, -3.04682329],
       [ 2.20050966, -3.04682329],
       [ 1.53836507,  1.81564138],
       [ 1.14398415, -3.04682329],
       [ 0.96423575, -0.14867487],
       [ 4.05822686,  1.41546978],
       [ 0.86779197, -3.04682329],
       [ 1.47047178, -3.04682329],
       [ 2.62965541, -0.06519324],
       [ 3.57303867, -3.04682329],
       [ 2.64082456, -3.04682329],
       [ 4.38632947,  4.46865541],
       [ 4.68837617,  0.15170498],
       [ 2.80619085,  2.1862174 ],
       [ 5.1576556 ,  1.48358496],
       [ 1.97218106,  1.16019973],
       [ 1.50539132, -3.04682329],
       [ 2.405815  , -3.04682329],
       [ 2.4476837 ,  0.70905618],
       [ 2.02537914,  0.89264674],
       [ 2.77953036,  1.9076072 ],
       [ 1.30215667,  1.69791103],
       [ 1.34992319, -0.27178604],
       [ 3.31375854, -3.04682329],
       [ 2.25662015,

In [68]:
dfmerged["#sum_counts_chick1"] = clrX[:,0]
dfmerged["#sum_counts_chick2"] = clrX[:,1]
dfmerged

#Datasets  #sum_counts_chick1  #sum_counts_chick2
0                Bacteroides fragilis            3.415293            0.879244
1        Bacteroides thetaiotaomicron            1.610047           -3.046823
2            Fusobacterium mortiferum            3.656630            2.301349
3              Fusobacterium ulcerans            3.321748           -3.046823
4                Fusobacterium varium            5.113107           -3.046823
..                                ...                 ...                 ...
77          Faecalitalea cylindroides           -1.944429            0.571396
78       Massilimicrobiota timonensis           -1.944429           -0.390617
79             Traorella massiliensis           -1.944429           -0.023466
80  Phascolarctobacterium sp. CAG:266           -1.944429            0.164853
81              Megamonas rupellensis           -1.944429           -0.237532

[82 rows x 3 columns]

In [69]:
dfmerged.to_csv('Fifth_Attempt_data_MR&clr_chick1_chick2.csv')